apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    kubernetes.io/service-name: external-node-exporter
addressType: IPv4
ports:
  - name: metrics
    port: 9100
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.100.79"