apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 62.6.0
    helm:
      skipCrds: false
      values: |
        grafana:
          adminPassword: admin
          service:
            type: ClusterIP
        prometheus:
          enabled: true
          prometheusSpec:
            storageSpec:
              emptyDir:
                medium: Memory
            additionalScrapeConfigs: |
              - job_name: 'external-node-exporter'
                static_configs:
                  - targets: ['192.168.100.79:9100']
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # --- ADD THIS SYNC OPTION AS A SAFEGUARD ---
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true