apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://helm.localstack.cloud
    targetRevision: 0.6.* # Locks to a minor version while getting patches
    helm:
      values: |
        image:
          name: localstack/localstack
          tag: 3.4.0
        service:
          type: ClusterIP # Use ClusterIP for internal cluster traffic
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack # Target namespace for LocalStack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:              # <-- Added this block
      - CreateNamespace=true  # <-- Correct syntax for ArgoCD namespaces